version: "3.9"
services:
  backend:
    build: ./server
    container_name: deepguard-backend
    restart: unless-stopped
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./logs/suricata:/app/logs/suricata:ro
      - ./logs/zeek:/app/logs/zeek:ro          # backend reads zeek logs here
    depends_on:
      db:
        condition: service_healthy   # ← waits until MySQL is actually ready
  frontend:
    build: ./front
    container_name: deepguard-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: deepguard-mysql
    restart: unless-stopped
    env_file:
      - ./server/.env
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.12.0
    container_name: deepguard-filebeat
    user: root
    network_mode: "host"
    volumes:
      - ./configs/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs/suricata:/var/log/suricata:ro
      - ./logs/zeek:/usr/local/zeek/logs/current:ro   # ← keep your filebeat.yml paths unchanged
    command: ["--strict.perms=false"]
    restart: unless-stopped

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    container_name: deepguard-logstash
    network_mode: "host"
    volumes:
      - ./configs/logstash/pipeline:/usr/share/logstash/pipeline:ro
    restart: unless-stopped

  suricata:
    image: jasonish/suricata:latest
    container_name: deepguard-suricata
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./logs/suricata:/var/log/suricata
      - ./suricata-config:/etc/suricata
    command: -c /etc/suricata/suricata.yaml -i ens33
    restart: unless-stopped

  zeek:
    image: zeek/zeek:8.1.0
    container_name: deepguard-zeek
    restart: unless-stopped
    network_mode: host
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./configs/zeek:/usr/local/zeek/etc:ro
      - ./logs/zeek:/usr/local/zeek/logs/current      # ← Zeek writes here, host sees ./logs/zeek
      - /opt/zeek/share/zeek/site:/usr/local/zeek/share/zeek/site
    command: sh -c "mkdir -p /usr/local/zeek/logs/current &&
                 zeek -i ens33 local -C Log::default_logdir=/usr/local/zeek/logs/current"
          #zeek -i ens33 local -C Log::default_logdir=/usr/local/zeek/logs/current
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
