version: "3.9"

services:

  backend:
    build: ./server
    container_name: deepguard-backend
    restart: unless-stopped

  frontend:
    build: ./front
    container_name: deepguard-frontend
    ports:
      - "80:80"
    restart: unless-stopped 
    depends_on:
      - backend
