FROM node:18-alpine

WORKDIR /app

RUN apk update && apk add docker-cli

COPY package*.json ./
RUN npm install

# Install nodemon globally for hot reloading
RUN npm install -g nodemon

EXPOSE 5000

# Run nodemon against your main entry file (adjust if it's index.js)
CMD ["npm", "run", "dev"]