import React, { useState, useEffect } from 'react';
import { useParams, useSearchParams } from 'react-router-dom';
import axios from 'axios';
import ExecutiveSummary from '../components/reports/ExecutiveSummary';
import EndpointFleetHealth from '../components/reports/EndpointFleetHealth';
import IncidentPostMortem from '../components/reports/IncidentPostMortem';
import DeepGuardAiAnomalies from '../components/reports/DeepGuardAiAnomalies';

/**
 * A specialized "Clean" view of reports designed for Puppeteer to print to PDF.
 * It removes all navigation, buttons, and site-wide layouts.
 */
const ReportPrintView = () => {
    const { templateId } = useParams();
    const [searchParams] = useSearchParams();
    const [data, setData] = useState(null);
    const [loading, setLoading] = useState(true);

    const hours = searchParams.get('hours') || 24;
    const ip = searchParams.get('ip');

    useEffect(() => {
        const fetchData = async () => {
            try {
                let endpoint = '';
                let method = 'get';
                let body = null;

                switch (templateId) {
                    case 'executive':
                        endpoint = `/reports/executive?hours=${hours}`;
                        break;
                    case 'endpoint':
                        endpoint = `/reports/endpoint-health?hours=${hours}`;
                        break;
                    case 'postmortem':
                        endpoint = `/reports/postmortem`;
                        method = 'post';
                        body = { hours, ip };
                        break;
                    case 'ai':
                        endpoint = `/reports/ai-anomalies?hours=${hours}`;
                        break;
                    default:
                        throw new Error('Invalid template');
                }

                const res = method === 'post' 
                    ? await axios.post(`${import.meta.env.VITE_BACK}${endpoint}`, body)
                    : await axios.get(`${import.meta.env.VITE_BACK}${endpoint}`);
                
                setData(res.data);
            } catch (err) {
                console.error("Print view fetch error:", err);
            } finally {
                setLoading(false);
            }
        };

        fetchData();
    }, [templateId, hours, ip]);

    if (loading) return <div className="p-10 text-text-secondary">Preparing for print...</div>;
    if (!data) return <div className="p-10 text-red-400">Failed to load report data for printing.</div>;

    return (
        <div className="bg-background-dark min-h-screen p-10 text-text-main print-mode">
            <div className="max-w-5xl mx-auto space-y-8">
                {/* Branding for PDF */}
                <div className="flex justify-between items-center border-b border-primary/30 pb-6 mb-10">
                    <div>
                        <h1 className="text-3xl font-bold text-gradient">DeepGuard SOC</h1>
                        <p className="text-text-secondary font-mono text-xs mt-1 uppercase tracking-widest">Autonomous Intrusion Detection & Response</p>
                    </div>
                    <div className="text-right">
                        <div className="text-sm font-bold text-text-main">Automated Security Report</div>
                        <div className="text-xs text-text-secondary mt-1">{new Date().toLocaleString()}</div>
                    </div>
                </div>

                {/* Template Content */}
                {templateId === 'executive' && <ExecutiveSummary data={data} />}
                {templateId === 'endpoint' && <EndpointFleetHealth data={data} />}
                {templateId === 'postmortem' && <IncidentPostMortem data={data} />}
                {templateId === 'ai' && <DeepGuardAiAnomalies data={data} />}

                {/* Footer for PDF */}
                <div className="mt-20 pt-8 border-t border-gray-800 text-center">
                    <p className="text-xs text-gray-600 font-mono italic">
                        This document is a confidential security record generated by the DeepGuard Platform. 
                        Unauthorized reproduction or distribution is strictly prohibited.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default ReportPrintView;
