FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

EXPOSE 3000
# or 5173 if you are using Vite

# Starts the React development server
CMD ["npm", "run", "dev"] 
# (Note: change to "npm start" if you are using Create React App)